apiVersion: v1
kind: ServiceAccount
metadata:
  name: context-testing-sa
  namespace: context-testing
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: context-testing-role
  namespace: context-testing
rules:
  - apiGroups: ["extensions"]
    resources: ["podsecuritypolicies"]
    resourceNames: ["context-testing-psp"]
    verbs: ["use"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: context-testing-rolebinding
  namespace: context-testing
subjects:
  - kind: ServiceAccount
    name: context-testing-sa
    namespace: context-testing
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: context-testing-role
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: context-testing-psp
  namespace: context-testing
spec:
  allowPrivilegeEscalation: false
  allowedHostPaths:
    - "/var/vcap"
  fsGroup:
    rule: RunAsAny
  requiredDropCapabilities:
    - ALL
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
    - "hostPath"
