---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-data
  labels:
    type: aws
    storage: small
spec:
  storageClassName: aws
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi