---
kind: Pod
apiVersion: v1
metadata:
  name: task-pv-another-pod
  labels:
    type: aws
    storage: small
spec:
  volumes:
    - name: redis-data-storage
      persistentVolumeClaim:
        claimName: redis-data
  containers:
    - name: task-pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/hello/from/aws/ebs/"
          name: redis-data-storage
