---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: redis-data-volume
  labels:
    type: aws
    storage: small
spec:
  storageClassName: aws
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"