apiVersion: v1
kind: Service
metadata:
  name: auth-svc
  labels:
    app: auth
    group: pks-workshop
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      name: http
  selector:
    app: auth
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
    group: pks-workshop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: voor/pks-workshop-auth:latest
          env:
            - name: NODE_PORT
              value: "8080"
            - name: REDIS_HOST
              value: "redis-redis-ha.redis.svc.cluster.local"
            - name: OPENID_DISCOVERY_URL
              valueFrom:
              secretKeyRef:
                name: auth-secret
                key: OPENID_DISCOVERY_URL
            - name: OPENID_DISCOVERY_CLIENT_ID
              valueFrom:
              secretKeyRef:
                name: auth-secret
                key: OPENID_DISCOVERY_CLIENT_ID
            - name: OPENID_DISCOVERY_CLIENT_SECRET
              valueFrom:
              secretKeyRef:
                name: auth-secret
                key: OPENID_DISCOVERY_CLIENT_SECRET
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
---

